services:
  - type: web
    name: portfolio-website
    runtime: php
    env: production
    region: oregon
    buildCommand: curl -sS https://getcomposer.org/installer | php
      php composer.phar install --optimize-autoloader --no-dev
      npm install
      npm run build
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:N6AYwqK8NoD5Zv/R/qDtIcd7UEte311hgghvF00LqVo=
      - key: APP_URL
        value: https://portfolio-website-nk4z.onrender.com
