services:
  - type: web
    name: Moiz_portfolio
    runtime: php
    region: oregon
    buildCommand: |
      composer install --optimize-autoloader --no-dev
      npm install
      npm run build
      php artisan migrate --force
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: php artisan serve --host 0.0.0.0 --port 8000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false